version: "3"
services:
  ubuntu:
    image: "futafi/docker-sudo"
    container_name: "x11-socket"
    privileged: true
    network_mode: "host"
    # user: '$(id -u):$(id -g)'
    user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}
